<CurrentWeather@BoxLayout>:
    location: ['New York', 'US']
    conditions: None
    temp: None
    temp_min: None
    temp_max: None
    orientation: "vertical"

    Label:
        text: app.root.format_location(root.location)
    BoxLayout:
        orientation: "horizontal"
        size_hint_y: None
        height: "40dp"

        Button:
            text: "Add location"
            on_press: app.root.show_add_location_form()
        Button:
            text: "Forecast"