<Locations@BoxLayout>:
    orientation: "vertical"
    locations_list: locations_list

    ListView:
        id: locations_list
        adapter:
            ListAdapter(
            data=[],
            cls=main.LocationButton,
            args_converter=main.args_converter)
    BoxLayout:
        orientation: "horizontal"
        size_hint_y: None
        height: "40dp"
        Button:
            text: "Add Location"
            on_press: app.root.show_add_location_form()